--------------------------------------------------------
--  File created - Monday-August-19-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BOARDVIEW_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MINIPROJ1"."BOARDVIEW_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence BOARD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MINIPROJ1"."BOARD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LOGS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MINIPROJ1"."LOGS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 33 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MINIPROJ1"."USERS_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "MINIPROJ1"."BOARD" 
   (	"NO" NUMBER(10,0), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"VIEW" NUMBER(20,0) DEFAULT 0, 
	"REGDATE" DATE, 
	"LAST_EDIT_AT" DATE, 
	"PASSWORD" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOGS
--------------------------------------------------------

  CREATE TABLE "MINIPROJ1"."LOGS" 
   (	"NO" NUMBER(7,0), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"EVENT" VARCHAR2(10 BYTE), 
	"TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "MINIPROJ1"."USERS" 
   (	"NO" NUMBER(7,0), 
	"ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"GENDER" NUMBER(1,0), 
	"CREATED_AT" DATE, 
	"ADMIN" NUMBER(1,0) DEFAULT 0, 
	"LAST_LOGIN" DATE, 
	"LAST_LOGOUT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS_DELETED
--------------------------------------------------------

  CREATE TABLE "MINIPROJ1"."USERS_DELETED" 
   (	"NO" NUMBER(7,0), 
	"ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"GENDER" NUMBER(1,0), 
	"CREATED_AT" DATE, 
	"DELETED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MINIPROJ1.BOARD
SET DEFINE OFF;
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (1,'skk3010','title','dddd
sss
',1,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'3010');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (3,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (4,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (5,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (6,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (7,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (8,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (9,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (10,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (11,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (12,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (13,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (14,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (15,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (16,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (17,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (18,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (19,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (20,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (21,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (22,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (23,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (24,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (25,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (26,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (27,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (28,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (29,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (30,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (31,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (32,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (33,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (34,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (35,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (36,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (37,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (38,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (39,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (40,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (41,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (42,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (43,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (44,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (45,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (46,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (47,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (48,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (49,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (50,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (51,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (52,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (53,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (54,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (55,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (56,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (57,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (58,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (59,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (60,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (61,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (62,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (63,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (64,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (65,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (66,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (67,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (68,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (69,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (70,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (71,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (72,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (73,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (74,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (75,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (76,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (77,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (78,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (79,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (80,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (81,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (82,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (83,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (84,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (85,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (86,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (87,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (88,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (89,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (90,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (91,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (92,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (93,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (94,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (95,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (96,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (97,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (98,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (99,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
Insert into MINIPROJ1.BOARD (NO,USER_ID,TITLE,CONTENT,"VIEW",REGDATE,LAST_EDIT_AT,PASSWORD) values (100,'유저1','제목1','내용1',0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'),'0');
REM INSERTING into MINIPROJ1.LOGS
SET DEFINE OFF;
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (1,'skk3010','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (3,'skk3010','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (7,'javajava','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (9,'javajava','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (11,'javajava','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (12,'javajava','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (13,'javajava','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (14,'javajava','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (15,'admin','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (17,'testacc','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (23,'skk3010','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (24,'skk3010','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (25,'skk3010','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (26,'skk3010','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (27,'skk3010','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (29,'skk3010','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (31,'skk3010','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (2,'skk3010','log out',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (4,'skk3010','log out',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (5,'javajava','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (8,'javajava','log out',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (10,'javajava','log out',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (20,'admin','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (21,'admin','log out',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (6,'javajava','log out',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (16,'admin','log out',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (18,'testacc','log out',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (22,'testacc2','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (28,'skk3010','log in',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (30,'skk3010','log out',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (32,'skk3010','log out',to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.LOGS (NO,USER_ID,EVENT,TIME) values (19,'testacc','log in',to_date('24/08/19','RR/MM/DD'));
REM INSERTING into MINIPROJ1.USERS
SET DEFINE OFF;
Insert into MINIPROJ1.USERS (NO,ID,PASSWORD,NAME,PHONE,ADDRESS,GENDER,CREATED_AT,ADMIN,LAST_LOGIN,LAST_LOGOUT) values (2,'skk3010','java!12345','김나인','010-4447-0985','소하로 162',1,to_date('24/08/16','RR/MM/DD'),0,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.USERS (NO,ID,PASSWORD,NAME,PHONE,ADDRESS,GENDER,CREATED_AT,ADMIN,LAST_LOGIN,LAST_LOGOUT) values (1,'admin','admin!0000','김구','010-4447-0985','구의로 15',1,to_date('24/08/16','RR/MM/DD'),1,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.USERS (NO,ID,PASSWORD,NAME,PHONE,ADDRESS,GENDER,CREATED_AT,ADMIN,LAST_LOGIN,LAST_LOGOUT) values (10,'java001','kosa123!@','유저1','010–4392-8457','서울시 종로구 명륜5가',1,to_date('24/08/19','RR/MM/DD'),0,null,null);
REM INSERTING into MINIPROJ1.USERS_DELETED
SET DEFINE OFF;
Insert into MINIPROJ1.USERS_DELETED (NO,ID,PASSWORD,NAME,PHONE,ADDRESS,GENDER,CREATED_AT,DELETED_AT) values (8,'testacc','acc!123','테스트','010-0000-0000','서울',2,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.USERS_DELETED (NO,ID,PASSWORD,NAME,PHONE,ADDRESS,GENDER,CREATED_AT,DELETED_AT) values (7,'javajava','java1234!@#$','김자바','010-0505-1234','창경궁로 24',2,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'));
Insert into MINIPROJ1.USERS_DELETED (NO,ID,PASSWORD,NAME,PHONE,ADDRESS,GENDER,CREATED_AT,DELETED_AT) values (9,'testacc2','testacc2!','테스트2','010-0000-0000','혜화',1,to_date('24/08/19','RR/MM/DD'),to_date('24/08/19','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINIPROJ1"."BOARD_PK" ON "MINIPROJ1"."BOARD" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINIPROJ1"."LOGS_PK" ON "MINIPROJ1"."LOGS" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINIPROJ1"."USERS_PK" ON "MINIPROJ1"."USERS" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINIPROJ1"."USERS_UNIQUE" ON "MINIPROJ1"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ADDLOGIN_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MINIPROJ1"."ADDLOGIN_TRG" 
AFTER
UPDATE OF last_login ON users 
FOR EACH ROW 
BEGIN 
	INSERT INTO LOGS (NO, user_id, event, time)
	VALUES (logs_seq.nextval, :NEW.id, 'log in', :NEW.LAST_LOGIN);
END;
/
ALTER TRIGGER "MINIPROJ1"."ADDLOGIN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ADDLOGOUT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MINIPROJ1"."ADDLOGOUT_TRG" 
AFTER
UPDATE OF last_logout ON users 
FOR EACH ROW 
BEGIN 
	INSERT INTO LOGS (NO, user_id, event, time)
	VALUES (logs_seq.nextval, :NEW.id, 'log out', :NEW.LAST_LOGIN);
END;
/
ALTER TRIGGER "MINIPROJ1"."ADDLOGOUT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DELETEUSER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MINIPROJ1"."DELETEUSER_TRG" 
AFTER 
DELETE ON users
FOR EACH ROW 
BEGIN 
	INSERT INTO USERS_DELETED (NO, id, password, name, phone, address, gender, created_at, deleted_at)
	VALUES (:OLD.NO, :OLD.id, :OLD.password, :OLD.name, :OLD.phone, :OLD.address, :OLD.gender, :OLD.created_at, sysdate);
END;
/
ALTER TRIGGER "MINIPROJ1"."DELETEUSER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Procedure LOGIN_PRO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MINIPROJ1"."LOGIN_PRO" (
	in_id IN users.id%type,
	out_pw OUT users.password%type 
)
IS
BEGIN
	SELECT password INTO out_pw FROM users
	WHERE id = in_id;
END;

/
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "MINIPROJ1"."USERS" MODIFY ("NO" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MINIPROJ1"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS" ADD CONSTRAINT "USERS_UNIQUE" UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MINIPROJ1"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS" MODIFY ("ADMIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS_DELETED
--------------------------------------------------------

  ALTER TABLE "MINIPROJ1"."USERS_DELETED" MODIFY ("NO" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS_DELETED" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS_DELETED" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS_DELETED" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS_DELETED" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS_DELETED" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS_DELETED" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS_DELETED" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."USERS_DELETED" MODIFY ("DELETED_AT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "MINIPROJ1"."BOARD" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."BOARD" MODIFY ("NO" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."BOARD" ADD CONSTRAINT "BOARD_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MINIPROJ1"."BOARD" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."BOARD" MODIFY ("VIEW" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."BOARD" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."BOARD" MODIFY ("LAST_EDIT_AT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOGS
--------------------------------------------------------

  ALTER TABLE "MINIPROJ1"."LOGS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."LOGS" MODIFY ("NO" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."LOGS" ADD CONSTRAINT "LOGS_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MINIPROJ1"."LOGS" MODIFY ("EVENT" NOT NULL ENABLE);
  ALTER TABLE "MINIPROJ1"."LOGS" MODIFY ("TIME" NOT NULL ENABLE);
